modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="easypathforge"
version="1.0.0"
displayName="Easy Path Forge"
description='''
A Minecraft Forge mod that provides a path shovel item to help players build paths easily.
'''

[[dependencies.easypathforge]]
modId="forge"
mandatory=true
versionRange="[47.3.11,)"
ordering="NONE"
side="BOTH"

[[dependencies.easypathforge]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
